service: my-app

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: src/handler.hello
    layers:
      - "${cf:my-layers-dev.PythonDashappDashdependenciesLambdaLayerQualifiedArn}"
